schema = """
        scalar Scalar1
        scalar Scalar2
        scalar Scalar3
        scalar Scalar4
        scalar Scalar5
        scalar Scalar6
        directive @q(arg: Scalar1) on QUERY
        directive @w(arg: Scalar2!) on QUERY
        directive @e(arg: [Scalar3]) on QUERY
        directive @r(arg: [Scalar4!]) on QUERY
        directive @t(arg: [Scalar5]!) on QUERY
        directive @y(arg: [Scalar6!]!) on QUERY
      """
