kind = "schema"
schema = "type A { id: ID! } type AGeneralError { message: String! } type AForbiddenError { message: String! }"

[options]
acceptedIdNames = ["id"]
acceptedIdTypes = ["ID"]

[options.exceptions]
types = ["AGeneralError", "AForbiddenError"]
