        type A {
          deprecatedWithoutReason: String @deprecated
          deprecatedWithReason: String @deprecated(reason: "Reason")
          notDeprecated: String
        }

        enum TestEnum {
          item1 @deprecated
          item2 @deprecated(reason: "Reason")
        }

        interface TestInterface {
          item1: String @deprecated
          item2: Number @deprecated(reason: "Reason")
          item3: String
          item4: String @deprecated(reason: "")
          item5: String @deprecated(reason: "  ")
        }

        type MyQuery @deprecated

        input MyInput {
          foo: String! @deprecated
        }
      