schema = """
        type RootQuery
        type RootMutation
        type RootSubscription

        schema {
          query: RootQuery
          mutation: RootMutation
          subscription: RootSubscription
        }
      """
