[package]
name = "rglint-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
apollo-parser.workspace = true
apollo-compiler.workspace = true
miette.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
globset.workspace = true
walkdir.workspace = true
ignore.workspace = true
rayon.workspace = true
xxhash-rust.workspace = true
regex.workspace = true
jsonschema.workspace = true
linkme.workspace = true
