kind = "schema"
schema = """
        interface Node {
          id: ID!
        }
        type User implements Node {
          id: ID!
        }
        type AEdge {
          node: User!
          cursor: String!
        }
        type AConnection {
          edges: [AEdge]
        }
      """

[options]
shouldImplementNode = true
