[package]
name = "rglint-graphql-spec"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["native"]
native = ["rglint-core/native"]
napi = ["rglint-core/napi"]

[dependencies]
rglint-core = { path = "../rglint-core", default-features = false }
apollo-compiler.workspace = true
linkme.workspace = true
tracing.workspace = true

[dev-dependencies]
rglint-test-harness = { path = "../rglint-test-harness" }
serde_json.workspace = true
