[package]
name = "rglint"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap.workspace = true
miette.workspace = true
serde.workspace = true
serde_json.workspace = true
rglint-core = { path = "../rglint-core" }
rglint-config = { path = "../rglint-config" }
rglint-graphql-spec = { path = "../rglint-graphql-spec" }
rglint-rules = { path = "../rglint-rules" }
walkdir.workspace = true

[dev-dependencies]
apollo-parser.workspace = true
assert_cmd = "2"
criterion.workspace = true
insta.workspace = true
jsonschema.workspace = true
predicates = "3"
tempfile.workspace = true

[[bench]]
name = "parser"
harness = false
path = "../../benches/parser.rs"

[[bench]]
name = "linters"
harness = false
path = "../../benches/linters.rs"
