[package]
name = "rglint"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap.workspace = true
miette.workspace = true
serde.workspace = true
serde_json.workspace = true
rglint-core = { path = "../rglint-core" }
rglint-config = { path = "../rglint-config" }
rglint-rules = { path = "../rglint-rules" }

[dev-dependencies]
insta.workspace = true
jsonschema.workspace = true
