documents = """
            fragment UserFields on User {
              name
            }
          """
schema = """
  type User {
    id: ID
    name: String
    posts: [Post]
  }

  type Post {
    id: ID
    title: String
    author: [User!]!
  }

  type Query {
    user: User
    userOrPost: UserOrPost
  }

  union UserOrPost = User | Post"""
