        type Query {
          user: User
        }
        type User {
          id: ID!
          name: String!
          friends(first: Int, after: String): FriendConnection!
        }
        type FriendConnection {
          edges: [FriendEdge]
          pageInfo: PageInfo!
        }
        type FriendEdge {
          cursor: String!
          node: Friend!
        }
        type Friend {
          id: ID!
          name: String!
        }
        type PageInfo {
          hasPreviousPage: Boolean!
          hasNextPage: Boolean!
          startCursor: String
          endCursor: String
        }
      