[package]
name = "rglint-config"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["native"]
native = ["rglint-core/native"]
napi = ["rglint-core/napi"]

[dependencies]
rglint-core = { path = "../rglint-core", default-features = false }
ahash.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
toml.workspace = true
jsonschema.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
