kind = "schema"

schema = """
        interface User {
          id: ID!
        }

        interface Manager implements User {
          id: ID!
        }

        type TopManager implements Manager {
          id: ID!
          name: String
        }

        type Query {
          me: User
        }
      """
