[package]
name = "rglint-rules"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rglint-core = { path = "../rglint-core" }
rglint-derive = { path = "../rglint-derive" }
apollo-parser.workspace = true
linkme.workspace = true
serde.workspace = true
serde_json.workspace = true
regex.workspace = true
thiserror.workspace = true

[dev-dependencies]
rglint-test-harness = { path = "../rglint-test-harness" }
insta.workspace = true
