schema = """
        type PageInfo
        type AEdge {
          node: [PageInfo!]!
          cursor: [PageInfo!]!
        }
        type AConnection {
          edges: [AEdge]
          pageInfo: PageInfo!
        }
      """

[options]
listTypeCanWrapOnlyEdgeType = false
shouldImplementNode = false
