sibling_documents = ["01.sibling.graphql"]
documents = """
            fragment UserLightFields on User {
              ... on User {
                id
              }
            }
            fragment UserMediumFields on User {
              ...UserLightFields
            }
            fragment UserFullFields on User {
              ...UserMediumFields
            }
          """
schema = """
  type User {
    id: ID
    name: String
    posts: [Post]
  }

  type Post {
    id: ID
    title: String
    author: [User!]!
  }

  type Query {
    user: User
    userOrPost: UserOrPost
  }

  union UserOrPost = User | Post"""
