[package]
name = "rglint-test-harness"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rglint-core = { path = "../rglint-core" }
apollo-parser.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
thiserror.workspace = true
insta.workspace = true
pretty_assertions.workspace = true

[dev-dependencies]
rglint-derive = { path = "../rglint-derive" }
linkme.workspace = true
proptest.workspace = true
tempfile.workspace = true