schema = "type B { id: ID! } type Bresult { key: String! } type BPayload { bool: Boolean! } type BPagination { num: Int! }"

[options]
acceptedIdNames = ["id"]
acceptedIdTypes = ["ID"]

[options.exceptions]
suffixes = ["Result", "Payload"]
