kind = "schema"
schema = """
        type User {
          id: ID!
        }
        type Query {
          user: User
        }
        type Mutation {
          createUser: User
        }
        type Subscription {
          userAdded: User
        }
      """
